/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as FiscalRouteImport } from './routes/fiscal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendasNovaRouteImport } from './routes/vendas.nova'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalRoute = FiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasNovaRoute = VendasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => VendasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fiscal': typeof FiscalRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pdv': typeof PdvRoute
  '/pedidos': typeof PedidosRoute
  '/vendas': typeof VendasRouteWithChildren
  '/vendas/nova': typeof VendasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fiscal': typeof FiscalRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pdv': typeof PdvRoute
  '/pedidos': typeof PedidosRoute
  '/vendas': typeof VendasRouteWithChildren
  '/vendas/nova': typeof VendasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fiscal': typeof FiscalRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pdv': typeof PdvRoute
  '/pedidos': typeof PedidosRoute
  '/vendas': typeof VendasRouteWithChildren
  '/vendas/nova': typeof VendasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fiscal'
    | '/orcamentos'
    | '/pdv'
    | '/pedidos'
    | '/vendas'
    | '/vendas/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fiscal'
    | '/orcamentos'
    | '/pdv'
    | '/pedidos'
    | '/vendas'
    | '/vendas/nova'
  id:
    | '__root__'
    | '/'
    | '/fiscal'
    | '/orcamentos'
    | '/pdv'
    | '/pedidos'
    | '/vendas'
    | '/vendas/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FiscalRoute: typeof FiscalRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PdvRoute: typeof PdvRoute
  PedidosRoute: typeof PedidosRoute
  VendasRoute: typeof VendasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal': {
      id: '/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof FiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/nova': {
      id: '/vendas/nova'
      path: '/nova'
      fullPath: '/vendas/nova'
      preLoaderRoute: typeof VendasNovaRouteImport
      parentRoute: typeof VendasRoute
    }
  }
}

interface VendasRouteChildren {
  VendasNovaRoute: typeof VendasNovaRoute
}

const VendasRouteChildren: VendasRouteChildren = {
  VendasNovaRoute: VendasNovaRoute,
}

const VendasRouteWithChildren =
  VendasRoute._addFileChildren(VendasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FiscalRoute: FiscalRoute,
  OrcamentosRoute: OrcamentosRoute,
  PdvRoute: PdvRoute,
  PedidosRoute: PedidosRoute,
  VendasRoute: VendasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
